# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='creator name')),
                ('profile_url', models.URLField(verbose_name='creator profile')),
            ],
        ),
        migrations.CreateModel(
            name='Prezi',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('thumbnail', models.URLField(verbose_name='thumbnail')),
                ('created_on', models.DateField(blank=True, null=True, verbose_name='created on')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prezis', to='prezi.Creator', verbose_name='creator')),
            ],
        ),
    ]
