# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 12:15
from __future__ import unicode_literals
import datetime, json

from django.db import migrations


data = json.load(open('./prezis.json'))


def create_initial_data(apps, shema_editor):
    """Create initial objects from the given json"""
    Creator = apps.get_model('prezi','Creator')
    Prezi = apps.get_model('prezi','Prezi')

    for prezi in data:
        name = prezi["creator"]["name"]
        profile_url = prezi["creator"]["profileUrl"]

        creator = Creator.objects.create(name=name, profile_url=profile_url)

        # create datetime object from string
        created_on = datetime.datetime.strptime(prezi["createdAt"], "%B %d, %Y")

        Prezi.objects.create(id=prezi['id'],
                                title=prezi['title'],
                                thumbnail=prezi['thumbnail'],
                                created_on=created_on,
                                creator=creator
                                )

def remove_initial_data(apps, shema_editor):
    Creator = apps.get_model('prezi','Creator')
    Prezi = apps.get_model('prezi','Prezi')

    Creator.objects.all().delete()
    Prezi.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('prezi', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data, remove_initial_data),
    ]

